version: '3.8'

services:
  guia-tgs:
    build:
      context: .
      dockerfile: Dockerfile
    image: guia-5-tgs:latest
    container_name: guia-5-tgs
    restart: unless-stopped
    expose:
      - "80"
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
